version: "3.8"
services:
  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - LINKEDIN_EMAIL=${LINKEDIN_EMAIL}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
